version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    ports:
      - '3305:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  myapp:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      spring.jpa.properties.hibernate.dialct: org.hibernate.dialect.MYSQL8Dialect
      spring.jpa.hibernate.ddl-auto: create-drop
      logging.level.org.hibernate: info
      logging.level.org.hibernate.SQL: debug
      spring.jpa.properties.hibernate.format_sql: 'true'
      springdoc.swagger-ui.operationsSorter: method
      application-description: mentorship API
      application-version: 1.0

volumes:
  mysql-data: